### ISSUE TITLE
[Feature Request]: support CJK text in filter

### ISSUE THREAD

**Issue by lost22git** [mdgrs-mei/PowerShellRun#10]
### OS

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Not specific to an OS

### New feature description

filter can not input CJK text

**Comment by mdgrs-mei** [comment]
Hi @lost22git 

This was mentioned [here](https://github.com/mdgrs-mei/PowerShellRun/pull/7#issuecomment-1966541739) and I can imagine how to implement it.

Let me work on it soon.

**Comment by mdgrs-mei** [comment]
Non-ascii characters are supported with the latest main branch. I'm preparing for the release now.

**Comment by mdgrs-mei** [comment]
@lost22git 

[v0.1.0](https://github.com/mdgrs-mei/PowerShellRun/releases/tag/v0.1.0) has been released.

Please reopen this issue if it doesn't work. Thank you.
