### ISSUE TITLE
[Feature Request]: Consider adding command aliases

### ISSUE THREAD

**Issue by jdhitsolutions** [mdgrs-mei/PowerShellRun#47]
### OS

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [X] Not specific to an OS

### New feature description

The command names in the module are long, which is perfectly acceptable. But the purpose of the module, as I see it anyway, is to make is easier for the user to do things without a lot of typing. I think you could almost create a domain specific language for this module like Pester. Instead of having to type `Invoke-PSRun`, let me type `psrun`. That's just one example.

**Comment by mdgrs-mei** [comment]
Thank you for the suggestion.

If we add aliases in the module, we need to care about the name conflicts with other modules or aliases that users define. Even if we don't add aliases, users can still create aliases that users prefer. For these reasons, I currently see more benefits on not adding aliases in the module.

As talked in another discussion, this module requires a profile script. I think it should be acceptable to define aliases there if they need.

**Comment by mdgrs-mei** [comment]
As a design choice, this module will not add aliases and users can still create aliases as their preference.
