### ISSUE TITLE
Is this the best the community and PowerShell team member can do!?

### ISSUE THREAD

**Issue by dfinke** [mdgrs-mei/PowerShellRun#54]
### OS

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [X] Not specific to an OS

### New feature description

https://github.com/Textualize/rich

This is what the PowerShell community wants!

Guessing we won't get it from the PowerShell team.

Hasn't been any real innovation out of the PowerShell team in years.

#sad

**Comment by mdgrs-mei** [comment]
PowerShellRun is a terminal based launcher and fuzzy finder, not a module for text formatting. It is out of the scope of this module.

However, I'm a bit curious which feature in the Rich interested you the most.

**Comment by Hrxn** [comment]
I'd have pointed you towards https://github.com/ShaunLawrie/PwshSpectreConsole, but it seems like you're already listed as a contributor there, which implies that you know about this already.

Also a bit curious about what exactly you had in mind here, @dfinke
