### ISSUE TITLE
[Bug]: Add-PSRunEntryGroup not working

### ISSUE THREAD

**Issue by jdhitsolutions** [mdgrs-mei/PowerShellRun#58]
### OS

- [X] Windows
- [ ] macOS
- [ ] Linux

### PSVersionTable

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### What happened?

Upgraded to v 0.8.0. Modified my configuration script to use the new group feature.

```powershell
$Newsletter = Add-PSRunEntryGroup -Name Newsletter -PassThru -Icon '📰'
Add-PSRunFavoriteFolder -EntryGroup $Newsletter -Path $ENV:OneDrive\Behind -Name Behind -Description 'Newsletter'
```

But the group doesn't get created and there are no errors. If I run `Add-PSRunEntryGroup -Name Newsletter -PassThru` I would expect to see an object but I get nothing. Tried in several PowerShell 7 sessions.

**Comment by jdhitsolutions** [comment]
It was `Enable-PSRunEntry`. I never made the connection that I needed to enable the new `EntryGroup` category. That should be clearer in the documentation. I would also suggest documenting again the keys to navigate "up" from the group.

**Comment by mdgrs-mei** [comment]
Ok I'll update the documentation. I'll also consider adding warnings when we add entries to a disavled category.
