### ISSUE TITLE
[Bug]: Error with composite emojis

### ISSUE THREAD

**Issue by jdhitsolutions** [mdgrs-mei/PowerShellRun#63]
### OS

- [X] Windows
- [ ] macOS
- [ ] Linux

### PSVersionTable

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### What happened?

I am using this emoji I grabbed from the Windows emoji picker: 🧑🏻‍💻
But it looks like this is a combination of  🧑🏻💻 Because that is what I see when I run PowerShellRun.

![image](https://github.com/user-attachments/assets/6d13c738-bd5f-4156-8873-5e083a909572)

**Comment by mdgrs-mei** [comment]
Does your terminal render 🧑🏻‍💻 correctly? I remember Windows Terminal could not render some emojis.

**Comment by jdhitsolutions** [comment]
Interesting. It renders in some terminals but not all. But even in the console where I can paste the emoji, PowerShell Run still is problematic.

![image](https://github.com/user-attachments/assets/65e479f3-da22-4431-8be0-f332134f50b8)

**Comment by mdgrs-mei** [comment]
You can see 3 or 4 spaces after the pasted emoji. That is stil not rendering it correctly. Even if I can fix the issue that is splitting it into 2 emojis, it will still break the layout.

I can only say for now please avoid using those emojis. There is a section about the limitations. I'll add some more explanations there.

**Comment by jdhitsolutions** [comment]
I recall now the known limitation. And I've accepted rendering problems. I often have to insert a space into the name to align things. I think some emojis simply have a little more white space than others.

**Comment by mdgrs-mei** [comment]
It turned out Windows Terminal was able to render the emoji correctly and the issue was caused by PowerShellRun. I'm working on this.

**Comment by mdgrs-mei** [comment]
The issue has been fixed. From the next release, you can use more emojis without breaking the rendering.

![image](https://github.com/user-attachments/assets/6b3504db-f33b-4fd2-bb71-5003b736fd29)
