### ISSUE TITLE
[Feature Request]: -Category parameter should be case insensitive

### ISSUE THREAD

**Issue by mdgrs-mei** [mdgrs-mei/PowerShellRun#8]
### OS

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [X] Not specific to an OS

### New feature description

`-Category All` works but `-Category all` does not work. It should also allow lower cases.

**Comment by AndrewPla** [comment]
Thanks for opening up this issue, mdgrs. I'll give this a look and see what I can do
